body:
  - type: dropdown
    attributes:
      label: "💻 变更类型 | Change Type"
      options:
        - ✨ feat
        - 🐛 fix
        - 💄 style
        - 🔨 chore
        - 📝 docs
        - other
    validations:
      required: true
  - type: textarea
    attributes:
      label: "🔀 变更说明 | Description of Change"
      description: Thank you for your Pull Request. Please provide a description above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "📝 补充信息 | Additional Information"
      description: Add any other context about the Pull Request here.